### PR TITLE
docs(Select): add a11y demo for select

### PR DESCRIPTION
**Pull request by bindoon**
增加了一个无障碍的文档

### CODE REVIEW

**Comment by youluna** [comment]
这个功能为什么不内置到select里呢？有什么考虑吗

**Comment by bindoon** [comment]
想过内置，但是 aria-live="assertive" 这个属性不知道是否适合放在组件里面

**Comment by youluna** [comment]
Balloon set aria-live="polite" in https://github.com/alibaba-fusion/next/pull/477/files#diff-f7a250af06668b424f6e57faaae96603 
we discussed this in https://github.com/alibaba-fusion/next/issues/439

I think it's OK to set aria-live in Select, but can it be "polite" instead of "assertive"?


@jdkahn Frank is not sure whether it is suitable for a component to set aria-live in. what's your opinion?

**Comment by bindoon** [comment]
seems good, i will use aria-live="polite" in the select.

but popupContent should still use onToggleHighlightItem

**Pull request closed without merging**
