### PR TITLE
support Row,Form component(function)

### PR DESCRIPTION
**Pull request by bojoyzhou**
support Row,Form component(function)

### CODE REVIEW

**Comment by guanpu** [comment]
Hi @bojoyzhou , Thank you very much for the PR, glad to see people trying contributing to this repo. Would you please describe the feature/issue you want to solve with this PR? If it is all about customize the className as shown in your test cases, then you can directly specify 'className' props to the <Row> element, like this `<Row className='cus-component'></Row>`, if you need any type of customized element like the title of this PR, maybe `PropTypes.element` is better than `PropTypes.func` as in your code. But I don't think we want any type of elements to be used as Row's container element.

So still welcome PR to any existing issue in the issue-pool, but for this one, currently I don't see any needs.

**Comment by bojoyzhou** [comment]
In many cases.
e.g.
```
<Row key={idx} component={Form} field={this.field} gutter="10">
    <Col fixedSpan="2">{idx + 1}</Col>
    <Col component={FormItem}>
        <Input name="name" placeholder="联系人" />
    </Col>
    <Col component={FormItem}>
        <OtAddress name="loadingAddress" placeholder="省/市/区/县" disabled={disabled} style={{ width: '100%' }} />
    </Col>
    <Col component={FormItem}>
        <Input name="address" placeholder="详细地址" />
    </Col>
    <Col component={FormItem}>
        <Input name="email" placeholder="邮箱" />
    </Col>
    <Col component={FormItem}>
        <Input name="mobile" placeholder="联系方式" />
    </Col>
</Row>
```

**Comment by bojoyzhou** [comment]
Maybe, you could scan all the source code to process `PropTypes.oneOfType([PropTypes.string, PropTypes.func])` @guanpu . I will fix files I changed.

**Comment by guanpu** [comment]
> In many cases.
> e.g.
> 
> ```
> <Row key={idx} component={Form} field={this.field} gutter="10">
>     <Col fixedSpan="2">{idx + 1}</Col>
>     <Col component={FormItem}>
>         <Input name="name" placeholder="联系人" />
>     </Col>
>     <Col component={FormItem}>
>         <OtAddress name="loadingAddress" placeholder="省/市/区/县" disabled={disabled} style={{ width: '100%' }} />
>     </Col>
>     <Col component={FormItem}>
>         <Input name="address" placeholder="详细地址" />
>     </Col>
>     <Col component={FormItem}>
>         <Input name="email" placeholder="邮箱" />
>     </Col>
>     <Col component={FormItem}>
>         <Input name="mobile" placeholder="联系方式" />
>     </Col>
> </Row>
> ```

Okay. If you really need to use in this manner, please resolve conflicts and so that we can merge it.

**Comment by bojoyzhou** [comment]
> PropTypes.element

`PropTypes.element` mean `A React element`, in this case it is wrong. `PropTypes.oneOfType([PropTypes.string, PropTypes.func])` is right.

**Pull request merged**
