### PR TITLE
fix(Collapse): fix nested collapse icon

### PR DESCRIPTION
**Pull request by jdkahn**

### CODE REVIEW

**Comment by youluna** [comment]
@tao1991123 please check this carefully! Will  the PR have any bad impact on users? Someone who uses old css stylesheet and new js files

**Comment by jdkahn** [comment]
@tao1991123 Is it possible to do that? Wouldn't users have to use both styles and js files from the same version?

**Comment by youluna** [comment]
>  Wouldn't users have to use both styles and js files from the same version?

No, they don't. Users who use theme package( https://github.com/alibaba-fusion/next/blob/master/site/en-us/theme.md ) use both `@alifd/next` and `@alifd/theme-xxx` as their dependencies. `@alifd/theme-xxx`  is generated based on a specific version of `@alifd/next`. `@alifd/theme-xxx` is published by users via Config Platform (fusion.design). The publish of `@alifd/theme-xxx` is more frequent than `@alifd/next`.

So version of css will always older than the js version( among the same minor verison ). Many users use it this way.

Users should keep css and js version in the same minor version.
e.g.
1.12.2 css with 1.12.2 js    ---> Fusion ensure it works.
1.12.2 css with 1.12.6 js    ---> Fusion ensure it works.
1.12.2 css with 1.13.6 js    ---> Users should update the theme package

**Comment by tao1991123** [comment]
@youluna  means  user writes css styles to overwrite the default style.


Only one case that users  overwrite
```css
.panel-expanded .icon {
xxxxx
}
```
but new style is priorer than the old

```css
.panel .icon.icon-expand {
xxxx
}
```
I reviewed and I think it's ok, you remove none of old classnames, it compatible.
I mean there is nearly no user who did this.

so I approved

**Comment by youluna** [comment]
close https://github.com/alibaba-fusion/next/issues/416

**Pull request merged**
